pipeline {
    agent any
    parameters {
        string(name: 'TARGET_DEVICE', defaultValue: 'rimmer.aencoin.com', description: 'Where should the built wallet be pushed to?')
        string(name: 'TARGET_PATH', defaultValue: '/home/apache/public_html/wallet.aencoin.io', description: 'Where (on the device file system) should the build be pushed to?')
        string(name: 'BASE_URL', defaultValue: 'https://wallet.aencoin.io', description: 'The base URL the project is expecting')
    }

    stages {

        stage('Checkout Repositories') {
            steps {
                dir('wallet') {
                  git credentialsId: '6e8fe423-1a29-43f4-a5b1-13b307c4c679', url: 'git@github.com:AENCO-Global/chain-wallet.git'
                }
            }
        }

        stage('Project Install') {
						steps {
						    dir('wallet/app') {
                    // TODO Remove the install of cross-env once going beyond standard node image
                    sh 'ls -la && yarn install'
                }
            }
        }

        stage('Run tests') {
            steps {
                dir('wallet/app') {
                    sh 'yarn run test'
                }
            }
        }

        stage('Build Distribution') {
						steps {
                dir('wallet/app') {
                    writeFile file: '.env', text: "BASE_URL=${params.BASE_URL}"
                    // Update the version
                    script {
                        def props = readJSON file: 'globals.json'
                        props.build_number = env.BUILD_NUMBER
                        writeJSON file: 'globals.json', json: props, pretty: 4
                    }
                    sh "yaen run build"
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                dir('wallet/app') {
										sh 'ls -la dist'
										// TODO If using Jenkins (rather than local keyring), change following lines
										// withCredentials([sshUserPrivateKey(credentialsId: 'sshTest', keyFileVariable: 'keyFile', passphraseVariable: 'passphrase', usernameVariable: 'username')]) {
                    //     sh "echo scp -r -i ${keyFile} dist ${username}@${params.TARGET_DEVICE}:${params.TARGET_PATH}"
                    //     sh "scp -r -i ${keyFile} dist ${username}@${params.TARGET_DEVICE}:${params.TARGET_PATH}"
                    // }
										sh "scp -r dist/* ${params.TARGET_DEVICE}:${params.TARGET_PATH}"

                }
           }
        }
    }
}
